
# This file is automatically generated, you probably don't want to edit this

bancovaOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "bancovaOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dep = NULL,
            fixed = NULL,
            random = NULL,
            covs = NULL,
            fixedPrior = 0.5,
            randomPrior = 1,
            covPrior = 0.354,
            modelTerms = NULL,
            plotHAxis = NULL,
            plotSepLines = NULL,
            plotSepPlots = NULL,
            plotError = "ci",
            ciWidth = 95,
            nullRow = -1,
            paramRow = -1,
            sort = NULL,
            nParamIters = 10000, ...) {

            super$initialize(
                package='BayesFactor',
                name='bancova',
                requiresData=TRUE,
                ...)

            private$..dep <- jmvcore::OptionVariable$new(
                "dep",
                dep,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "continuous",
                    "nominal",
                    "ordinal"))
            private$..fixed <- jmvcore::OptionVariables$new(
                "fixed",
                fixed,
                suggested=list(
                    "nominal",
                    "ordinal"),
                default=NULL)
            private$..random <- jmvcore::OptionVariables$new(
                "random",
                random,
                suggested=list(
                    "nominal",
                    "ordinal"),
                default=NULL)
            private$..covs <- jmvcore::OptionVariables$new(
                "covs",
                covs,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "continuous",
                    "nominal",
                    "ordinal"),
                default=NULL)
            private$..fixedPrior <- jmvcore::OptionNumber$new(
                "fixedPrior",
                fixedPrior,
                min=0.1,
                max=2,
                default=0.5)
            private$..randomPrior <- jmvcore::OptionNumber$new(
                "randomPrior",
                randomPrior,
                min=0.1,
                max=2,
                default=1)
            private$..covPrior <- jmvcore::OptionNumber$new(
                "covPrior",
                covPrior,
                min=0.1,
                max=2,
                default=0.354)
            private$..modelTerms <- jmvcore::OptionArray$new(
                "modelTerms",
                modelTerms,
                template=jmvcore::OptionGroup$new(
                    "modelTerms",
                    NULL,
                    elements=list(
                        jmvcore::OptionArray$new(
                            "term",
                            NULL,
                            template=jmvcore::OptionString$new(
                                "term",
                                NULL)),
                        jmvcore::OptionBool$new(
                            "assumed",
                            NULL))),
                default=NULL)
            private$..plotHAxis <- jmvcore::OptionVariable$new(
                "plotHAxis",
                plotHAxis,
                default=NULL)
            private$..plotSepLines <- jmvcore::OptionVariable$new(
                "plotSepLines",
                plotSepLines,
                default=NULL)
            private$..plotSepPlots <- jmvcore::OptionVariable$new(
                "plotSepPlots",
                plotSepPlots,
                default=NULL)
            private$..plotError <- jmvcore::OptionList$new(
                "plotError",
                plotError,
                options=list(
                    "none",
                    "ci",
                    "se"),
                default="ci")
            private$..ciWidth <- jmvcore::OptionNumber$new(
                "ciWidth",
                ciWidth,
                min=50,
                max=99.9,
                default=95)
            private$..nullRow <- jmvcore::OptionInteger$new(
                "nullRow",
                nullRow,
                default=-1,
                hidden=TRUE)
            private$..paramRow <- jmvcore::OptionInteger$new(
                "paramRow",
                paramRow,
                default=-1,
                hidden=TRUE)
            private$..sort <- jmvcore::OptionSort$new(
                "sort",
                sort,
                default=NULL,
                hidden=TRUE,
                passive=TRUE)
            private$..nParamIters <- jmvcore::OptionInteger$new(
                "nParamIters",
                nParamIters,
                min=1,
                default=10000)

            self$.addOption(private$..dep)
            self$.addOption(private$..fixed)
            self$.addOption(private$..random)
            self$.addOption(private$..covs)
            self$.addOption(private$..fixedPrior)
            self$.addOption(private$..randomPrior)
            self$.addOption(private$..covPrior)
            self$.addOption(private$..modelTerms)
            self$.addOption(private$..plotHAxis)
            self$.addOption(private$..plotSepLines)
            self$.addOption(private$..plotSepPlots)
            self$.addOption(private$..plotError)
            self$.addOption(private$..ciWidth)
            self$.addOption(private$..nullRow)
            self$.addOption(private$..paramRow)
            self$.addOption(private$..sort)
            self$.addOption(private$..nParamIters)
        }),
    active = list(
        dep = function() private$..dep$value,
        fixed = function() private$..fixed$value,
        random = function() private$..random$value,
        covs = function() private$..covs$value,
        fixedPrior = function() private$..fixedPrior$value,
        randomPrior = function() private$..randomPrior$value,
        covPrior = function() private$..covPrior$value,
        modelTerms = function() private$..modelTerms$value,
        plotHAxis = function() private$..plotHAxis$value,
        plotSepLines = function() private$..plotSepLines$value,
        plotSepPlots = function() private$..plotSepPlots$value,
        plotError = function() private$..plotError$value,
        ciWidth = function() private$..ciWidth$value,
        nullRow = function() private$..nullRow$value,
        paramRow = function() private$..paramRow$value,
        sort = function() private$..sort$value,
        nParamIters = function() private$..nParamIters$value),
    private = list(
        ..dep = NA,
        ..fixed = NA,
        ..random = NA,
        ..covs = NA,
        ..fixedPrior = NA,
        ..randomPrior = NA,
        ..covPrior = NA,
        ..modelTerms = NA,
        ..plotHAxis = NA,
        ..plotSepLines = NA,
        ..plotSepPlots = NA,
        ..plotError = NA,
        ..ciWidth = NA,
        ..nullRow = NA,
        ..paramRow = NA,
        ..sort = NA,
        ..nParamIters = NA)
)

bancovaResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        main = function() private$.items[["main"]],
        descPlot = function() private$.items[["descPlot"]],
        descPlots = function() private$.items[["descPlots"]],
        state = function() private$.items[["state"]],
        param = function() private$.items[["param"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Bayesian ANCOVA")
            self$add(jmvcore::Table$new(
                options=options,
                name="main",
                title="ANCOVA",
                rowSelect="(nullRow)",
                sortSelect="(sort)",
                clearWith=list(
                    "dep",
                    "fixed",
                    "random",
                    "covs",
                    "modelTerms"),
                columns=list(
                    list(
                        `name`="name", 
                        `title`="Model", 
                        `type`="text", 
                        `sortable`=TRUE),
                    list(
                        `name`="bf", 
                        `title`="BF\u2081\u2080", 
                        `sortable`=TRUE),
                    list(
                        `name`="err", 
                        `title`="error %"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="descPlot",
                title="Descriptive Plot",
                visible="(plotHAxis)",
                width=500,
                height=300,
                renderFun=".descPlot",
                clearWith=list(
                    "dep",
                    "plotHAxis",
                    "plotSepLines",
                    "plotSepPlots",
                    "plotError",
                    "ciWidth")))
            self$add(jmvcore::Array$new(
                options=options,
                name="descPlots",
                title="Descriptive Plots",
                visible="(plotSepPlots)",
                template=jmvcore::Image$new(
                    options=options,
                    title="$key",
                    renderFun=".descPlot",
                    clearWith=list(
                        "dep",
                        "plotHAxis",
                        "plotSepLines",
                        "plotSepPlots",
                        "plotError",
                        "ciWidth"))))
            self$add(jmvcore::State$new(
                options=options,
                name="state",
                clearWith=list(
                    "dep",
                    "fixed",
                    "random",
                    "covs",
                    "modelTerms")))
            self$add(jmvcore::Table$new(
                options=options,
                name="param",
                title="Parameter estimates",
                rowSelect="(paramRow)",
                columns=list(
                    list(
                        `name`="param", 
                        `title`="Parameter", 
                        `type`="text"),
                    list(
                        `name`="mean", 
                        `title`="Mean", 
                        `type`="number"))))}))

bancovaBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "bancovaBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'BayesFactor',
                name = 'bancova',
                version = c(1,0,0),
                options = options,
                results = bancovaResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE)
        }))

#' Bayesian ANCOVA
#'
#' Analysis of Covariance
#'
#' @examples
#' data('ToothGrowth')
#'
#' bancova(ToothGrowth, dep = 'len', factors = 'supp', covs = 'dose')
#'
#' @param data the data as a data frame
#' @param dep a string naming the dependent variable from \code{data},
#'   variable must be numeric
#' @param fixed a vector of strings naming the fixed factors from \code{data}
#' @param random a vector of strings naming the random factors from
#'   \code{data}
#' @param covs a vector of strings naming the covariates from \code{data}
#' @param fixedPrior .
#' @param randomPrior .
#' @param covPrior .
#' @param modelTerms .
#' @param plotHAxis a string naming the variable placed on the horizontal axis
#'   of the plot
#' @param plotSepLines a string naming the variable represented as separate
#'   lines on the plot
#' @param plotSepPlots a string naming the variable to separate over to form
#'   multiple plots
#' @param plotError \code{'none'}, \code{'ci'} (default), or \code{'se'}. Use
#'   no error bars, use credible intervals, or use standard errors on the plots,
#'   respectively
#' @param ciWidth a number between 50 and 99.9 (default: 95) specifying the
#'   credible interval width
#' @param nullRow .
#' @param paramRow .
#' @param sort .
#' @param nParamIters .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$main} \tab \tab \tab \tab \tab a table of ANCOVA results \cr
#'   \code{results$descPlot} \tab \tab \tab \tab \tab a descriptives plot \cr
#'   \code{results$descPlots} \tab \tab \tab \tab \tab an array of descriptives plots \cr
#'   \code{results$state} \tab \tab \tab \tab \tab a state \cr
#'   \code{results$param} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$main$asDF}
#'
#' \code{as.data.frame(results$main)}
#'
#' @export
bancova <- function(
    data,
    dep,
    fixed = NULL,
    random = NULL,
    covs = NULL,
    fixedPrior = 0.5,
    randomPrior = 1,
    covPrior = 0.354,
    modelTerms = NULL,
    plotHAxis = NULL,
    plotSepLines = NULL,
    plotSepPlots = NULL,
    plotError = "ci",
    ciWidth = 95,
    nullRow = -1,
    paramRow = -1,
    sort = NULL,
    nParamIters = 10000) {

    if ( ! requireNamespace('jmvcore'))
        stop('bancova requires jmvcore to be installed (restart may be required)')

    options <- bancovaOptions$new(
        dep = dep,
        fixed = fixed,
        random = random,
        covs = covs,
        fixedPrior = fixedPrior,
        randomPrior = randomPrior,
        covPrior = covPrior,
        modelTerms = modelTerms,
        plotHAxis = plotHAxis,
        plotSepLines = plotSepLines,
        plotSepPlots = plotSepPlots,
        plotError = plotError,
        ciWidth = ciWidth,
        nullRow = nullRow,
        paramRow = paramRow,
        sort = sort,
        nParamIters = nParamIters)

    results <- bancovaResults$new(
        options = options)

    analysis <- bancovaClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
