
# This file is automatically generated, you probably don't want to edit this

banovaOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "banovaOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dep = NULL,
            fixed = NULL,
            random = NULL,
            fixedPrior = 0.5,
            randomPrior = 1,
            modelTerms = NULL,
            plotHAxis = NULL,
            plotSepLines = NULL,
            plotSepPlots = NULL,
            plotError = "ci",
            ciWidth = 95,
            nullRow = -1,
            sort = NULL, ...) {

            super$initialize(
                package='BayesFactor',
                name='banova',
                requiresData=TRUE,
                ...)

            private$..dep <- jmvcore::OptionVariable$new(
                "dep",
                dep,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..fixed <- jmvcore::OptionVariables$new(
                "fixed",
                fixed,
                suggested=list(
                    "nominal",
                    "ordinal"),
                default=NULL)
            private$..random <- jmvcore::OptionVariables$new(
                "random",
                random,
                suggested=list(
                    "nominal",
                    "ordinal"),
                default=NULL)
            private$..fixedPrior <- jmvcore::OptionNumber$new(
                "fixedPrior",
                fixedPrior,
                min=0.1,
                max=2,
                default=0.5)
            private$..randomPrior <- jmvcore::OptionNumber$new(
                "randomPrior",
                randomPrior,
                min=0.1,
                max=2,
                default=1)
            private$..modelTerms <- jmvcore::OptionTerms$new(
                "modelTerms",
                modelTerms,
                default=NULL)
            private$..plotHAxis <- jmvcore::OptionVariable$new(
                "plotHAxis",
                plotHAxis,
                default=NULL)
            private$..plotSepLines <- jmvcore::OptionVariable$new(
                "plotSepLines",
                plotSepLines,
                default=NULL)
            private$..plotSepPlots <- jmvcore::OptionVariable$new(
                "plotSepPlots",
                plotSepPlots,
                default=NULL)
            private$..plotError <- jmvcore::OptionList$new(
                "plotError",
                plotError,
                options=list(
                    "none",
                    "ci",
                    "se"),
                default="ci")
            private$..ciWidth <- jmvcore::OptionNumber$new(
                "ciWidth",
                ciWidth,
                min=50,
                max=99.9,
                default=95)
            private$..nullRow <- jmvcore::OptionInteger$new(
                "nullRow",
                nullRow,
                default=-1,
                hidden=TRUE)
            private$..sort <- jmvcore::OptionSort$new(
                "sort",
                sort,
                default=NULL,
                hidden=TRUE,
                passive=TRUE)

            self$.addOption(private$..dep)
            self$.addOption(private$..fixed)
            self$.addOption(private$..random)
            self$.addOption(private$..fixedPrior)
            self$.addOption(private$..randomPrior)
            self$.addOption(private$..modelTerms)
            self$.addOption(private$..plotHAxis)
            self$.addOption(private$..plotSepLines)
            self$.addOption(private$..plotSepPlots)
            self$.addOption(private$..plotError)
            self$.addOption(private$..ciWidth)
            self$.addOption(private$..nullRow)
            self$.addOption(private$..sort)
        }),
    active = list(
        dep = function() private$..dep$value,
        fixed = function() private$..fixed$value,
        random = function() private$..random$value,
        fixedPrior = function() private$..fixedPrior$value,
        randomPrior = function() private$..randomPrior$value,
        modelTerms = function() private$..modelTerms$value,
        plotHAxis = function() private$..plotHAxis$value,
        plotSepLines = function() private$..plotSepLines$value,
        plotSepPlots = function() private$..plotSepPlots$value,
        plotError = function() private$..plotError$value,
        ciWidth = function() private$..ciWidth$value,
        nullRow = function() private$..nullRow$value,
        sort = function() private$..sort$value),
    private = list(
        ..dep = NA,
        ..fixed = NA,
        ..random = NA,
        ..fixedPrior = NA,
        ..randomPrior = NA,
        ..modelTerms = NA,
        ..plotHAxis = NA,
        ..plotSepLines = NA,
        ..plotSepPlots = NA,
        ..plotError = NA,
        ..ciWidth = NA,
        ..nullRow = NA,
        ..sort = NA)
)

banovaResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        main = function() private$.items[["main"]],
        assump = function() private$.items[["assump"]],
        contrasts = function() private$.items[["contrasts"]],
        postHoc = function() private$.items[["postHoc"]],
        desc = function() private$.items[["desc"]],
        descPlot = function() private$.items[["descPlot"]],
        descPlots = function() private$.items[["descPlots"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Bayesian ANOVA")
            self$add(jmvcore::Table$new(
                options=options,
                name="main",
                title="ANOVA",
                columns=list()))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    homo = function() private$.items[["homo"]],
                    qq = function() private$.items[["qq"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="assump",
                            title="Assumption Checks")
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="homo",
                            title="Test for Homogeneity of Variances (Levene's)",
                            columns=list()))
                        self$add(jmvcore::Image$new(
                            options=options,
                            name="qq",
                            title="Q-Q Plot"))}))$new(options=options))
            self$add(jmvcore::Array$new(
                options=options,
                name="contrasts",
                title="Contrasts",
                template=jmvcore::Table$new(
                    options=options,
                    title="Contrasts - $key",
                    columns=list())))
            self$add(jmvcore::Array$new(
                options=options,
                name="postHoc",
                title="Post Hoc Tests",
                template=jmvcore::Table$new(
                    options=options,
                    title="",
                    columns=list())))
            self$add(jmvcore::Table$new(
                options=options,
                name="desc",
                title="Descriptives",
                columns=list()))
            self$add(jmvcore::Image$new(
                options=options,
                name="descPlot",
                title="Descriptive Plot"))
            self$add(jmvcore::Array$new(
                options=options,
                name="descPlots",
                title="Descriptive Plots",
                template=jmvcore::Image$new(
                    options=options,
                    title="$key",
                    renderFun=".descPlot")))}))

banovaBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "banovaBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'BayesFactor',
                name = 'banova',
                version = c(1,0,0),
                options = options,
                results = banovaResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = TRUE)
        }))

#' Bayesian ANOVA
#'
#' Analysis of Variance
#'
#' @examples
#' data('ToothGrowth')
#'
#' banova(ToothGrowth, dep = 'len', fixed = c('dose', 'supp'))
#'
#' @param data the data as a data frame
#' @param dep a string naming the dependent variable from \code{data},
#'   variable must be numeric
#' @param fixed a vector of strings naming the fixed factors from \code{data}
#' @param random a vector of strings naming the random factors from
#'   \code{data}
#' @param fixedPrior .
#' @param randomPrior .
#' @param modelTerms a list of character vectors describing the terms to go
#'   into the model
#' @param plotHAxis a string naming the variable placed on the horizontal axis
#'   of the plot
#' @param plotSepLines a string naming the variable represented as separate
#'   lines on the plot
#' @param plotSepPlots a string naming the variable to separate over to form
#'   multiple plots
#' @param plotError \code{'none'}, \code{'ci'} (default), or \code{'se'}. Use
#'   no error bars, use credible intervals, or use standard errors on the plots,
#'   respectively
#' @param ciWidth a number between 50 and 99.9 (default: 95) specifying the
#'   credible interval width
#' @param nullRow .
#' @param sort .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$main} \tab \tab \tab \tab \tab a table of ANOVA results \cr
#'   \code{results$assump$homo} \tab \tab \tab \tab \tab a table of homogeneity tests \cr
#'   \code{results$assump$qq} \tab \tab \tab \tab \tab a q-q plot \cr
#'   \code{results$contrasts} \tab \tab \tab \tab \tab an array of contrasts tables \cr
#'   \code{results$postHoc} \tab \tab \tab \tab \tab an array of post-hoc tables \cr
#'   \code{results$desc} \tab \tab \tab \tab \tab a table of descriptive statistics \cr
#'   \code{results$descPlot} \tab \tab \tab \tab \tab a descriptives plot \cr
#'   \code{results$descPlots} \tab \tab \tab \tab \tab an array of descriptives plots \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$main$asDF}
#'
#' \code{as.data.frame(results$main)}
#'
#' @export
banova <- function(
    data,
    dep,
    fixed = NULL,
    random = NULL,
    fixedPrior = 0.5,
    randomPrior = 1,
    modelTerms = NULL,
    plotHAxis = NULL,
    plotSepLines = NULL,
    plotSepPlots = NULL,
    plotError = "ci",
    ciWidth = 95,
    nullRow = -1,
    sort = NULL) {

    if ( ! requireNamespace('jmvcore'))
        stop('banova requires jmvcore to be installed (restart may be required)')

    if (missing(data))
        data <- jmvcore:::marshalData(
            parent.frame(),
            `if`( ! missing(dep), dep, NULL),
            `if`( ! missing(fixed), fixed, NULL),
            `if`( ! missing(random), random, NULL),
            `if`( ! missing(plotHAxis), plotHAxis, NULL),
            `if`( ! missing(plotSepLines), plotSepLines, NULL),
            `if`( ! missing(plotSepPlots), plotSepPlots, NULL))

    options <- banovaOptions$new(
        dep = dep,
        fixed = fixed,
        random = random,
        fixedPrior = fixedPrior,
        randomPrior = randomPrior,
        modelTerms = modelTerms,
        plotHAxis = plotHAxis,
        plotSepLines = plotSepLines,
        plotSepPlots = plotSepPlots,
        plotError = plotError,
        ciWidth = ciWidth,
        nullRow = nullRow,
        sort = sort)

    results <- banovaResults$new(
        options = options)

    analysis <- banovaClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
