
# This file is automatically generated, you probably don't want to edit this

blinRegOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "blinRegOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dep = NULL,
            covs = NULL,
            covPrior = 0.354,
            modelTerms = NULL, ...) {

            super$initialize(
                package='BayesFactor',
                name='blinReg',
                requiresData=TRUE,
                ...)

            private$..dep <- jmvcore::OptionVariable$new(
                "dep",
                dep,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..covs <- jmvcore::OptionVariables$new(
                "covs",
                covs,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"),
                default=NULL)
            private$..covPrior <- jmvcore::OptionNumber$new(
                "covPrior",
                covPrior,
                min=0.1,
                max=2,
                default=0.354)
            private$..modelTerms <- jmvcore::OptionTerms$new(
                "modelTerms",
                modelTerms,
                default=NULL)

            self$.addOption(private$..dep)
            self$.addOption(private$..covs)
            self$.addOption(private$..covPrior)
            self$.addOption(private$..modelTerms)
        }),
    active = list(
        dep = function() private$..dep$value,
        covs = function() private$..covs$value,
        covPrior = function() private$..covPrior$value,
        modelTerms = function() private$..modelTerms$value),
    private = list(
        ..dep = NA,
        ..covs = NA,
        ..covPrior = NA,
        ..modelTerms = NA)
)

blinRegResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        main = function() private$.items[["main"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Bayesian Linear Regression")
            self$add(jmvcore::Table$new(
                options=options,
                name="main",
                title="Linear Regression",
                columns=list(
                    list(
                        `name`="name", 
                        `title`="Model", 
                        `type`="text"),
                    list(
                        `name`="bf", 
                        `title`="BF\u2081\u2080"),
                    list(
                        `name`="err", 
                        `title`="error %"))))}))

blinRegBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "blinRegBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'BayesFactor',
                name = 'blinReg',
                version = c(1,0,0),
                options = options,
                results = blinRegResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = TRUE)
        }))

#' Bayesian Linear Regression
#'
#' 
#' @param data the data as a data frame
#' @param dep a string naming the dependent variable from \code{data},
#'   variable must be numeric
#' @param covs a vector of strings naming the covariates from \code{data}
#' @param covPrior .
#' @param modelTerms a list of character vectors describing the terms to go
#'   into the model
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$main} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$main$asDF}
#'
#' \code{as.data.frame(results$main)}
#'
#' @export
blinReg <- function(
    data,
    dep,
    covs = NULL,
    covPrior = 0.354,
    modelTerms = NULL) {

    if ( ! requireNamespace('jmvcore'))
        stop('blinReg requires jmvcore to be installed (restart may be required)')

    if (missing(data))
        data <- jmvcore:::marshalData(
            parent.frame(),
            `if`( ! missing(dep), dep, NULL),
            `if`( ! missing(covs), covs, NULL))

    options <- blinRegOptions$new(
        dep = dep,
        covs = covs,
        covPrior = covPrior,
        modelTerms = modelTerms)

    results <- blinRegResults$new(
        options = options)

    analysis <- blinRegClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
