
# This file is automatically generated, you probably don't want to edit this

bttestOneSOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "bttestOneSOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            bfType = "BF10",
            bfPrior = 0.707,
            testValue = 0,
            hypothesis = "different",
            meanDiff = FALSE,
            effectSize = FALSE,
            ci = FALSE,
            ciWidth = 95,
            desc = FALSE,
            miss = "perAnalysis",
            descPlot = FALSE,
            pp = FALSE,
            robust = FALSE, ...) {

            super$initialize(
                package='BayesFactor',
                name='bttestOneS',
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"),
                rejectInf=FALSE)
            private$..bfType <- jmvcore::OptionList$new(
                "bfType",
                bfType,
                options=list(
                    "BF10",
                    "BF01"),
                default="BF10")
            private$..bfPrior <- jmvcore::OptionNumber$new(
                "bfPrior",
                bfPrior,
                default=0.707,
                min=0.5,
                max=2)
            private$..testValue <- jmvcore::OptionNumber$new(
                "testValue",
                testValue,
                default=0)
            private$..hypothesis <- jmvcore::OptionList$new(
                "hypothesis",
                hypothesis,
                options=list(
                    "different",
                    "greater",
                    "less"),
                default="different")
            private$..meanDiff <- jmvcore::OptionBool$new(
                "meanDiff",
                meanDiff,
                default=FALSE)
            private$..effectSize <- jmvcore::OptionBool$new(
                "effectSize",
                effectSize,
                default=FALSE)
            private$..ci <- jmvcore::OptionBool$new(
                "ci",
                ci,
                default=FALSE)
            private$..ciWidth <- jmvcore::OptionNumber$new(
                "ciWidth",
                ciWidth,
                min=50,
                max=99.9,
                default=95)
            private$..desc <- jmvcore::OptionBool$new(
                "desc",
                desc,
                default=FALSE)
            private$..miss <- jmvcore::OptionList$new(
                "miss",
                miss,
                options=list(
                    "perAnalysis",
                    "listwise"),
                default="perAnalysis")
            private$..descPlot <- jmvcore::OptionBool$new(
                "descPlot",
                descPlot,
                default=FALSE,
                hidden=TRUE)
            private$..pp <- jmvcore::OptionBool$new(
                "pp",
                pp,
                default=FALSE)
            private$..robust <- jmvcore::OptionBool$new(
                "robust",
                robust,
                default=FALSE)

            self$.addOption(private$..vars)
            self$.addOption(private$..bfType)
            self$.addOption(private$..bfPrior)
            self$.addOption(private$..testValue)
            self$.addOption(private$..hypothesis)
            self$.addOption(private$..meanDiff)
            self$.addOption(private$..effectSize)
            self$.addOption(private$..ci)
            self$.addOption(private$..ciWidth)
            self$.addOption(private$..desc)
            self$.addOption(private$..miss)
            self$.addOption(private$..descPlot)
            self$.addOption(private$..pp)
            self$.addOption(private$..robust)
        }),
    active = list(
        vars = function() private$..vars$value,
        bfType = function() private$..bfType$value,
        bfPrior = function() private$..bfPrior$value,
        testValue = function() private$..testValue$value,
        hypothesis = function() private$..hypothesis$value,
        meanDiff = function() private$..meanDiff$value,
        effectSize = function() private$..effectSize$value,
        ci = function() private$..ci$value,
        ciWidth = function() private$..ciWidth$value,
        desc = function() private$..desc$value,
        miss = function() private$..miss$value,
        descPlot = function() private$..descPlot$value,
        pp = function() private$..pp$value,
        robust = function() private$..robust$value),
    private = list(
        ..vars = NA,
        ..bfType = NA,
        ..bfPrior = NA,
        ..testValue = NA,
        ..hypothesis = NA,
        ..meanDiff = NA,
        ..effectSize = NA,
        ..ci = NA,
        ..ciWidth = NA,
        ..desc = NA,
        ..miss = NA,
        ..descPlot = NA,
        ..pp = NA,
        ..robust = NA)
)

bttestOneSResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        ttest = function() private$.items[["ttest"]],
        desc = function() private$.items[["desc"]],
        plots = function() private$.items[["plots"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Bayesian One Sample T-Test")
            self$add(jmvcore::Table$new(
                options=options,
                name="ttest",
                title="One Sample T-Test",
                rows="(vars)",
                clearWith=list(
                    "hypothesis",
                    "testValue",
                    "miss",
                    "ciWidth"),
                columns=list(
                    list(
                        `name`="var", 
                        `title`="", 
                        `content`="($key)", 
                        `type`="text", 
                        `combineBelow`=TRUE),
                    list(
                        `name`="bf10", 
                        `title`="BF\u2081\u2080", 
                        `visible`="(bfType:BF10)"),
                    list(
                        `name`="bf01", 
                        `title`="BF\u2080\u2081", 
                        `visible`="(bfType:BF01)"),
                    list(
                        `name`="err", 
                        `title`="error %"),
                    list(
                        `name`="md", 
                        `title`="Mean difference", 
                        `type`="number", 
                        `visible`="(meanDiff)"),
                    list(
                        `name`="es", 
                        `title`="Cohen's d", 
                        `type`="number", 
                        `visible`="(effectSize)"),
                    list(
                        `name`="cil", 
                        `title`="Lower", 
                        `superTitle`="% Credible Interval", 
                        `type`="number", 
                        `visible`="(ci)"),
                    list(
                        `name`="ciu", 
                        `title`="Upper", 
                        `superTitle`="% Credible Interval", 
                        `type`="number", 
                        `visible`="(ci)"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="desc",
                title="Descriptives",
                visible="(desc)",
                rows="(vars)",
                clearWith=list(
                    "miss"),
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `content`="($key)", 
                        `type`="text"),
                    list(
                        `name`="num", 
                        `title`="N", 
                        `type`="integer"),
                    list(
                        `name`="mean", 
                        `title`="Mean", 
                        `type`="number"),
                    list(
                        `name`="sd", 
                        `title`="SD", 
                        `type`="number"))))
            self$add(jmvcore::Array$new(
                options=options,
                name="plots",
                title="Plots",
                items="(vars)",
                clearWith=list(
                    "miss",
                    "bfPrior",
                    "hypothesis",
                    "testValue"),
                template=R6::R6Class(
                    inherit = jmvcore::Group,
                    active = list(
                        desc = function() private$.items[["desc"]],
                        pp = function() private$.items[["pp"]],
                        robust = function() private$.items[["robust"]]),
                    private = list(),
                    public=list(
                        initialize=function(options) {
                            super$initialize(
                                options=options,
                                name="undefined",
                                title="$key")
                            self$add(jmvcore::Image$new(
                                options=options,
                                name="desc",
                                visible="(descPlot)",
                                renderFun=".desc",
                                clearWith=list()))
                            self$add(jmvcore::Image$new(
                                options=options,
                                name="pp",
                                visible="(pp)",
                                renderFun=".pp",
                                clearWith=list(
                                    "bfType"),
                                height=350,
                                width=450))
                            self$add(jmvcore::Image$new(
                                options=options,
                                name="robust",
                                visible="(robust)",
                                renderFun=".robust",
                                clearWith=list(
                                    "bfType"),
                                height=350,
                                width=470))}))$new(options=options)))}))

bttestOneSBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "bttestOneSBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'BayesFactor',
                name = 'bttestOneS',
                version = c(1,0,0),
                options = options,
                results = bttestOneSResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = TRUE)
        }))

#' Bayesian One Sample T-Test
#'
#' 
#'
#' @examples
#' data('ToothGrowth')
#'
#' bttestOneS(ToothGrowth, vars = c('len', 'dose'))
#'
#' @param data the data as a data frame
#' @param vars a vector of strings naming the variables of interest in
#'   \code{data}
#' @param bfType \code{'BF10'} (default) or \code{'BF01'}
#' @param bfPrior a number between 0.5 and 2 (default 0.707), the prior width
#'   to use in calculating Bayes factors
#' @param testValue a number specifying the value of the null hypothesis
#' @param hypothesis \code{'different'} (default), \code{'greater'} or
#'   \code{'less'}, the alternative hypothesis; different to \code{testValue},
#'   greater than \code{testValue}, and less than \code{testValue} respectively
#' @param meanDiff \code{TRUE} or \code{FALSE} (default), provide means and
#'   standard deviations
#' @param effectSize \code{TRUE} or \code{FALSE} (default), provide effect
#'   sizes
#' @param ci \code{TRUE} or \code{FALSE} (default), provide confidence
#'   intervals
#' @param ciWidth a number between 50 and 99.9 (default: 95), the width of
#'   confidence intervals
#' @param desc \code{TRUE} or \code{FALSE} (default), provide descriptive
#'   statistics
#' @param miss \code{'perAnalysis'} or \code{'listwise'}, how to handle
#'   missing values; \code{'perAnalysis'} excludes missing values for individual
#'   dependent variables, \code{'listwise'} excludes a row from all analyses if
#'   one of its entries is missing.
#' @param descPlot \code{TRUE} or \code{FALSE} (default), provide descriptive
#'   plots
#' @param pp .
#' @param robust .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$ttest} \tab \tab \tab \tab \tab a table containing the t-test results \cr
#'   \code{results$desc} \tab \tab \tab \tab \tab a table containing the descriptives \cr
#'   \code{results$plots} \tab \tab \tab \tab \tab an array of descriptive plots \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$ttest$asDF}
#'
#' \code{as.data.frame(results$ttest)}
#'
#' @export
bttestOneS <- function(
    data,
    vars,
    bfType = "BF10",
    bfPrior = 0.707,
    testValue = 0,
    hypothesis = "different",
    meanDiff = FALSE,
    effectSize = FALSE,
    ci = FALSE,
    ciWidth = 95,
    desc = FALSE,
    miss = "perAnalysis",
    descPlot = FALSE,
    pp = FALSE,
    robust = FALSE) {

    if ( ! requireNamespace('jmvcore'))
        stop('bttestOneS requires jmvcore to be installed (restart may be required)')

    if (missing(data))
        data <- jmvcore:::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL))

    options <- bttestOneSOptions$new(
        vars = vars,
        bfType = bfType,
        bfPrior = bfPrior,
        testValue = testValue,
        hypothesis = hypothesis,
        meanDiff = meanDiff,
        effectSize = effectSize,
        ci = ci,
        ciWidth = ciWidth,
        desc = desc,
        miss = miss,
        descPlot = descPlot,
        pp = pp,
        robust = robust)

    results <- bttestOneSResults$new(
        options = options)

    analysis <- bttestOneSClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
